project_id = "cwjrkygliokjseprelax"

[functions.import-csv]
verify_jwt = false

[functions.process-sql]
verify_jwt = false

[functions.dashboard-data]
verify_jwt = false

[functions.cedente-info]
verify_jwt = false

[functions.analyze-cedente]
verify_jwt = false

[functions.giro-carteira]
verify_jwt = false

[functions.external-db]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.bootstrap-master]
verify_jwt = false

[functions.portfolio-data]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false
